### ISSUE TITLE
Fix typo on infographic

### ISSUE THREAD

**Issue by realsanketnaik** [OWASP/www-project-top-10-for-large-language-model-applications#181]
At the bottom right, LLM05, supply chain is misspelt as "suply chain" in the infographic: 
[OWASP Top 10 for LLM Applications.png](https://github.com/OWASP/www-project-top-10-for-large-language-model-applications/blob/main/1_1_vulns/artifacts/infographics/OWASP%20Top%2010%20for%20LLM%20Applications.png)

**Comment by Bobsimonoff** [comment]
Thank you @realsanketnaik

**Comment by Bobsimonoff** [comment]
@GangGreenTemperTatum  @rossja  I have the fixed file but am not sure what process you want to follow for fixing images since they can't easily be versioned in github that I know of
![OWASP Top 10 for LLM Applications](https://github.com/OWASP/www-project-top-10-for-large-language-model-applications/assets/139978786/37b2aed8-fee1-4543-9180-134fca97c2f4)

**Comment by rossja** [comment]
I think if you just replace the image in the repository it should see the
file has changed and still track when you commit and push it?
It just replaces the whole thing rather than incrementally updating, afaik.

--
Jason

**Comment by rossja** [comment]
Makes sense, will do.

**Comment by rossja** [comment]
Done! PR 187

**Comment by Bobsimonoff** [comment]
Fix is included in 1.1
