### ISSUE TITLE
LLM03 - Potential Expand of Data Poisoning as a Topic to Cover Unintentional Safety-related Harm etc.

### ISSUE THREAD

**Issue by GangGreenTemperTatum** [OWASP/www-project-top-10-for-large-language-model-applications#251]
Discussion topics:

Should "`data poisoning`" be broadened as a category? Bending a model isn't entirely about the contents of the data being "bad," but about the outcomes of using any given data for training of the model.
Hear me out. You can 'bend' a model by any of these methods:
- backdoored data (e.g. a stop sign with a green square that means 'ignore me')
- data with toxic or protected content that might inadvertently come out during operation
- improper reinforcement (bias added resulting from the training process, for example)
- inappropriate guardrails/alignment testing during retraining
Should this top-10 item be more about model misalignment/re-alignment and cover poisoned data as a subset?

Example citation - https://arxiv.org/abs/2310.03693
Another obvious resource - https://www.ram-shankar.com/

[Internal Slack thread](https://owasp.slack.com/archives/C05F7JWFYBU/p1701355209279489)

**Comment by NerdAboutTown** [comment]
This does bring up an interesting point. I’ve been wondering why our top 10 doesn’t address things like alignment, bias, toxicity, and related negative outcomes. Training data poisoning would be the cause. So, I do agree with you as long as our top 10 is going to remain split between some of the top 10 items being vectors and others being results.Sent from my iPhoneOn Dec 1, 2023, at 10:03 PM, Ads Dawson ***@***.***> wrote:﻿
Discussion topics:
Should "data poisoning" be broadened as a category? Bending a model isn't entirely about the contents of the data being "bad," but about the outcomes of using any given data for training of the model.
Hear me out. You can 'bend' a model by any of these methods:

backdoored data (e.g. a stop sign with a green square that means 'ignore me')
data with toxic or protected content that might inadvertently come out during operation
improper reinforcement (bias added resulting from the training process, for example)
inappropriate guardrails/alignment testing during retraining
Should this top-10 item be more about model misalignment/re-alignment and cover poisoned data as a subset?

Example citation - https://arxiv.org/abs/2310.03693
Another obvious resource - https://www.ram-shankar.com/
Internal Slack thread

**Comment by jsotiro** [comment]
I agree with the proposal of broadening the category and also with Bob on the challenges of the vectors vs results split which will be with us forever and will reflect the imperfectibility of life refusing to fully fit into definitions.

Instead, I want us to become more explicit and concrete about the types of attacks so that defenders are equipped to recognize and defend against them. LLMs change what poisoning does. In Traditional ML it's all about misclassifications (Siamese Cat as Lion) or denial of service by lowering confidence levels. In LLMs, the innocuous-sounding term misalignment is removing the safety features of a model that the initial training had added and otherwise, you'd need to use jailbreaking at inference time to bypass.  
 
We should call this out explicitly and recommend tests on this. I will add this to the Supply Chain entry as an attack too - eg an attacker republishes a variation of say LLama but without the safety measures embedded into it, uploaded to Hugging Face, once i have researched the tests and validations Hugging Face applies to a submission.

Additionally, I also want us to discuss the role of **model tampering**. This is an additional way to "bend" the mode we currently don't coverl. And, interestingly, our Training Data Poisoning entry has a reference to [PoisonGPT: How we hid a lobotomized LLM on Hugging Face to spread fake news](https://blog.mithrilsecurity.io/poisongpt-how-we-hid-a-lobotomized-llm-on-hugging-face-to-spread-fake-news/) by Mithril Security. Yet the attack is not related to data poisoning at all. As the researchers point out, they locate and remove - post-training factual associations in the model  - i.e. "lobotomize" it. This is done by the likes of Microsoft for benevolent purposes - remove specific misbehaviors by Bing Chat - but as the researchers demonstrate can have the same effects as poisoning.

**Comment by jsotiro** [comment]
Having previewed the forthcoming NIST draft on Adversarial AI taxonomies, I see that need solves the problem by having a taxonomy of Poisoning attacks and in there it has various training data attacks (eg backdoors) and then an entry for model poisoniing which is about trojan horses. we could change the ntry to Data and Model Poisoning and cover the entire spectrum including the model tampering attacks

**Comment by chiffa** [comment]
I disagree. Training data poisoning attacks are currently trivial to implement and their mitigations are not yet routinely put in place. As such they deserve their top 3 position. 

I understand the desire to widen the scope, but that would have high chances to confuse the end users, and overlap with other separate concerns:

- Finite "gas" for fine tuning models, leading to a conflict between alignment axes (https://arxiv.org/abs/2212.08073). There are no known mitigations, nor even a consensus on how to prioritize axes, and given that it is usually done in-house, they are hard to attack (except for common SFT training datasets poisoning)
- White-box inspection - proof doors (https://arxiv.org/abs/2204.06974) are still in-research, requiring both highly sophisticated attackers and ability to modify final model, making it a separate concern, that should not be in the top 10 for most LLM operators and developers
- Backdoored data - if labeled properly - actually should increase the resilience of the model to the evasion attacks (which are closer to LLM001 - prompt injection anyway)

**Comment by chiffa** [comment]
> i think another perspective is not to limit specifically to data in training, but also include finetuning and contextual chatbot application sessions - I.E Microsoft Tay was not just limited to only training data.

You seem to be confusing pretraining with training. Generative pretraining is the step where massive texts are spread over thousands of GPUs burning millions in electricity. Fine-tuning, PEFT, RLHF, DPO, further pretraining - they all use smaller training datasets, but are still part of the training, given that the weights of the model are still modified

in short what you seem to want is "training dataset", and you seem to currently be confusing "training dataset" with "pretraining dataset".

Does that make sense?

**Comment by chiffa** [comment]
> .E, i host a REST API and integrate some sort of open-source model which has been backdoored/poisioned - https://www.darkreading.com/application-security/hugging-face-ai-platform-100-malicious-code-execution-models

Once again - these are three different concerns for me, that have different risks and mitigation strategies:

1. attacks on software stack running and distributing models => easy to implement, classical cyber-sec vectors; classical cyber-sec mitigations
2. malicious model backdoors on the weights level => reserved to advanced attackers with full model access, hard to diagnose, mitigation possible through data augmentation and weight fuzzing that is already recommended for model generalization
3. malicious data injection into training dataset => easy to implement, reasonably easy to make undetectable, pretty much impossible to detect on SotA LLM-scale datasets, especially for smaller developers, due to the need for manual analysis, or knowing what you are looking for in advance.

To me, 1 should not even be in the LLMs - it is a classical cyber-security attack with classical cyber-security mitigation, 2 and 3 are separate concerns, with 2 being a significantly smaller concern than 3 and requiring mitigation.

> we felt like beforehand, the entry was only pigeon-holed specifically on data (particularly pretraining) 

IMHO, it was pigeonholed for a reason (and if it was not, thank god it got), because it is a specific concern with specific threats, specific attacker capabilities assumptions, and specific mitigations.

Bundling it up with other concerns will make things significantly more confusing and less useful to ML stack or model developers.
